export {Home} from './Home'
export {Quiz} from './Quiz'
export {Result} from './Result'
export {Arena} from './Arena'
export {PageNotFound} from './PageNotFound'
export {PrivateRoute} from './PrivateRoute'